#!/usr/bin/env bash

## Generated by Google AI on 06/08/2026.

# Default variables
show_all=true
git_only=false
nongit_only=false

# Parse command-line options
while getopts "-:" opt; do
  case "$opt" in
    -)
      case "${OPTARG}" in
        show-git-only) git_only=true; show_all=false ;;
        show-nongit-only) nongit_only=true; show_all=false ;;
        *) echo "Unknown option: --${OPTARG}"; exit 1 ;;
      esac
      ;;
    *) echo "Usage: $0 [--show-git-only | --show-nongit-only]"; exit 1 ;;
  esac
done

# List directories and filter based on flags
for item in */; do
  # Remove trailing slash for git command
  dir_name="${item%/}"
  
  # Check if directory is a git repository
  is_git=$(git -C "$dir_name" rev-parse --is-inside-work-tree 2>/dev/null)

  # Apply the case statement for display logic
  case $1 in
    $("$show_all") )
      echo "[ALL] $item"
      ;;
    $("$git_only" && [[ "$is_git" == "true" ]]) )
      echo "[GIT] $item"
      ;;
    $("$nongit_only" && [[ -z "$is_git" ]]) )
      echo "[NON-GIT] $item"
      ;;
  esac
done

